site_name: Documentation

docs_dir: docs

nav: 
  - Home: index.md
  - Installation Guide: installation.md
  - API: api.md
  - Database: db.md
  - Logger: logger.md
  - Model: model.md

theme:
  name: material

